language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: orRVRm7CIqh5gwIKylA3fi1cHX0JxsXw7hm60PvcsoC1hRY8h9lkgxvWg/a7GhKZosyNnDlSeHkdw1ZDnMgbX79cYBUscNWQZQVCRZcMrHTDz+FYantPe6vpKPaxL/3B3W3VpnhZNulgDkhGnqtzPzYm3AXitCbzc14GtKBjMZHBIWOnaKEUxgYKprCBckhGjsobktUrb3ksKI6zPDX09FWQxsE0QKxn34nucI8jLuvgIyU8B7yImhSQ4MLSvEKyv66+fP2nt1/e02RsLOPQiLsLZRyK3jv9u7nxufbW5QJLpqc+zlQHZ4oOOAczMR5Uo+UNQQmmSzKAgWLOVB/8pCCRbJvT5nc/cowUAS2NOpnZIvGCUYTzaDq1iL3tRfiD1EF2P5kRkFgofMaiK7mGyTlZcwL8VFLmO4cjkimZpWQTJtvWsZI/Go5soLkLplnoOz0GgQ96pXZD75rTv/7h4QigUKulqaBNh6i8ClA8fwkNRY9QsN4XsRtxQDG4KlfBNhcQsowst3iPKFJTRFQCoYPb+rCXjBrS9d9JXisE31Dl/1yCGp7ygtYpcVJXWnDPpHh4qIJscyqpsNInVQv0RDOosVBLlUGR8kg3U4XT030HarELNn+PZPfQ6HEtn/R7+MY68SqyKlAiw/UPadEeC4AwTNaRAwGzlSRtQBouAck=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: sRziYRSmri4u7c0tGWU28WFtNaq+lSyxQpq+gtGUftoqihCaq2XrAbYoyaDAxb9B9k2XIchjzQrHR+txjjbOkmdnVd+8wniIIZCbdw5Fvbeky8JkA3j2BCdFCR4Njzv0exR/hSXVMKkJHBvS8E9wGIbIU6oB7jV/RUP72hXq/vP1qJLml70mYvMrj1+jurDBAS4P5Q9s0gOaONj/tn0NysscjqaxNh7IZtf7FHIpTW50aqTD6xP6bXGPuvZZTqn41LeT1QSt/XthwtEg2IlOWapjNwvaxBtgLv6ZbnbrEN68u07iNuEGzIKdBw4JD4M8mCEfHP7AOdO7fMUopkuveT6gwqI3MVLE43byY5GRdEV7mU1IJFTsaT+5jz389U4g3ahQCp/CDrKB8QqIpgvamExW3mN9CPYpvuhEwRFB5ejJzV3/9aeSj/LNxS/B+7QIhabyQd0oLI2zeDxV8TkOWtcmJJlLUkG7ZcrjkacQXRJ9MYUByC6HTIERzSKyErIwH6OZ5L5W+S9RmSGkRyosemgoaOziS10NCrHDtJvmcX/2DxgBGm6aIJSGKdnqmDgh23P1SkqmN9vcuoKBFem2lnY8ITkXXleYtNk/qh20f/VoaV3XUE5zIGDuKqzWgLR0EZWr0lDNN+q5PHBlGBTmsG+nAmaHzmIGUnuBwN8eQFY=
sudo: false
