language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: jWMsAqjU0ZMIc3tE3c3tq9CfeqtPRsw8ULHwgS+Flq2KVrrQ3SkDhSw3LP3JFp3+nRfa3r5LyU/cSh9Cecg1N3DPsW0CpMRX9Z1gVrzk72yPJWNdI6dEHmn00cyJbxPTCZH6gVGPA93iK4/w/Z7vgIc85LZYFg86G+ZGuydG0kBXk0svRRE14MH0fY+/JqoCv2SLwgy+MO2ZwOAEMQK13VtxqNhNPTEtaOhHq/l96CL+H1fwdvylNvDfkGY8GtcuN0rJiIE2stwWdKp5lyUCT6MSCn7tjxvFqAEUScwMz2ze31m7PPOHZ2ePZYh4PR7z9gHbtTXxGmT+XwmHDmXGqdc7ADrsZcmwl5toqlsccQq8icXFdOMlfkXy/GeYJsS2/rPrvjphUlNY6Q9zy+5UJTJrmK/XFG3ALbVCMK5vNslyqNLDu8ZpUjswrizLSsyYbBxaJt4JcGnN95Pj2yPqjOo1uF3AoC3f9vPOKWqSJN/CLXh4uf/eEg+DFA0/Gkt7XbSSv0WXv0ZHbRbczE9pofg0N8aNC7C1fGe0esm07rhjP1DOhwpXZB7zJTW2dnNmwDry/DhXHgtbMaeKF4UzMnpUYHgnnnCQEwzQ53T0BKRKxfA2cnTTx8uJI5uZohrDdCkyIb7lqJ1xN6f/nfQo1xvxhLvaO8iu1O3d/OhIWGk=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: Zb44xmYAeSGRv34JbVhLgPKhEvk2Vz2wzmP3D9DCzyYgolNWejRz8QIuyOGO3l3MYiKL+NDOw9ZfDujM5hdhkNrhxnkeDFWoDPKQK4giWnpJOE7PK/Dh/Ug1D21KCHImPTHOmyZMSALMm+VjpVHOiZOLDhTCr3insT1fBND2pJVIuERfxGsRTk5sB1GTaNPYovnUcRzG52mvO1M+FZI3ffbZjusJz7nJJNbbRRV3P8Sb5d0xo7z77t7pFV4r5Vo94PSbNg5wHrNgrWendpYMZ00L+Tg3iTZgUQb6KoSVa270Mc4oleom3q8QlwOWxU33UicJVFst6dMw3ad03GiD477bphd8GVpFZq5x76CLob/opLvV4EEQbBEg1J3fxL+ZvBhZSyA8dXIY9GenJ6fKiaS2w+X6e6E0QLZD7dvZuavvFJBxkQdiwPmkyLzTjSmVPrp6O81S0WbeaVK+MrqyHOE0zwjiZv9JsVGxJLASnK1rPI7cZgfkAad0Qt2WSyUdv8gTk6i4YIoAD/1XwY8zDoiCE+uMnx+MQPhBqgCcdt+y71sg5Hy7yumRpQMxNoBAYgG2oh6eF/mnrvErp5XSS2mfqTVrxXa+chuU+fsrdRlZENQ01Py2cpn4C9f53/25UmKd4U+N5S8lejpTaQgRi89vbBebuVJKGgam7sPyPHs=
sudo: false
